name: Build React App
on: [workflow_dispatch]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
